server:
  port: 9000
  servlet:
    context-path: /forum/api

logging:
  level:
    org: info

spring:
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:intech-forum-api}
    username: ${DB_USER:alexandergolovnya}
    password: ${DB_USER_PASS:root}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: POSTGRESQL
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect